version: "3.8"

services:
  account-postgres:
    image: library/postgres:11.9
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account
    ports:
      - "5432:5432"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    working_dir: /opt/kafka

  account-service:
    build: ../account-service
    ports:
      - "5001:8080"
      - "5011:8081"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - account-postgres